# Generated by Django 4.2 on 2025-07-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_shelf_category_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('other', 'その他'), ('hobby', '趣味')], max_length=100),
        ),
    ]
