# Generated by Django 4.2 on 2025-07-30 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_shelf_thumbnail_alter_shelf_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelf',
            name='category',
            field=models.CharField(choices=[('life', '生活'), ('hobby', '趣味'), ('business', 'ビジネス'), ('other', 'その他')], max_length=100),
        ),
    ]
