# Generated by Django 4.2 on 2025-08-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_shelf_user_alter_shelf_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='category',
            field=models.CharField(choices=[('life', '生活'), ('hobby', '趣味'), ('other', 'その他'), ('business', 'ビジネス')], max_length=100),
        ),
    ]
